### PR TITLE
 Link localhost URLs

### PR DESCRIPTION
**Pull request by djjuhasz**
- Update hugo
- Add angle brackets to http://localhost URLs to make them links.

### CODE REVIEW

**Review by sevein — COMMENTED** [review]
A couple of questions:

1. Are we sure that we want to commit the node_modules dir?
2. Should we also update the hugo version in https://github.com/artefactual-labs/enduro/blob/main/netlify.toml?
3. What's the public folder and the package.json file in the root?

**Comment by djjuhasz** [comment]
Answers below.

> A couple of questions:
> 
>     1. Are we sure that we want to commit the node_modules dir?

No, if it's not necessary.  I'm not clear how the whole Hugo + Docsy + node build pipeline works, so I wasn't sure if node_modules is a build artifact or required for the docs site. I'll `.gitignore` node_modules if we don't want it in the code base.


>     2. Should we also update the hugo version in https://github.com/artefactual-labs/enduro/blob/main/netlify.toml?

Yes. I missed that, sorry.

>     3. What's the public folder and the package.json file in the root?

Oohh, that's probably a result of me trying to run the hugo build using the go binary directly instead of using `make website`.  I'll delete those.

**Comment by djjuhasz** [comment]
@sevein I can't figure out why the Netlify build failed, can you have a look or add me to the project?

**Comment by sevein** [comment]
I will look at it in a bit.

**Review by sevein — APPROVED** [review]
LGTM

**Comment by djjuhasz** [comment]
Thanks @sevein!

**Pull request merged**
