### PR TITLE
workflow: handle parsing errors gracefully

### LINKED ISSUE #32: Problem: Non NHA naming conventions fail transfer
The problem of #9 has resurfaced in a new form. In 4d5fe1e53c5da576d92ba445b1fd8ca6594dd693 some additional NHA identifiers were introduced. The [nha parser](https://github.com/artefactual-labs/enduro/blob/4d5fe1e53c5da576d92ba445b1fd8ca6594dd693/internal/nha/parse.go) parses the filenames of uploads to Enduro. If the parsing fails the workflow fails with a non-retryable error.

I get that from the perspective of the NHA you want to fail if the naming convention is wrong, but from the perspective of a "general" tool, this is rather unfortunate. Do you already have any plans on how you want to approach this, and if so can I help in the implementation effort. Today's update to 19.2 broke my experimental environment.

I think the simplest solution at this point would be to introduce a basic parser. This parser will just strip the extension from the filename and that's it. You can switch between both parsers using a configuration flag. In a later stage, it might be worthwhile to introduce a way of configuring "custom" parsers, but I would say that it is not worth the time at this point.

Do you agree? If so I'll create a PR tomorrow. If not please let me know what you propose and if I can help.

### PR DESCRIPTION
**Pull request by sevein**
Fixes #32 and #33.

### CODE REVIEW

**Comment by sevein** [comment]
@jorikvankemenade, let me know what you think!

**Comment by jorikvankemenade** [comment]
I ran into one problem when running `make enduro-dev`:

```
internal/amclient/ingest.go:10: running "mockgen": exec: "mockgen": executable file not found in $PATH
internal/collection/collection.go:19: running "mockgen": exec: "mockgen": executable file not found in $PATH
internal/watcher/watcher.go:56: running "mockgen": exec: "mockgen": executable file not found in $PATH
```

Running `go get github.com/golang/mock/mockgen` before running any other `make` command fixed this problem. Am I doing something wrong in how I am building, or might this be a problem with the makefile? I think the rest of the solution looks fine! If I run into new problems I'll open an issue.

Thanks for fixing this so swiftly!

**Comment by sevein** [comment]
Maybe `make bingen` or `make tools` can help.

**Comment by jorikvankemenade** [comment]
I haven't checked `make bingen`, `make tools` resulted in the same error.

**Comment by jorikvankemenade** [comment]
Running `make bingen` unfortunately also results in the same error. However, apparently I made a mistake earlier. `make tools` installs the right dependencies.

**Pull request merged**
